version: "3.8"

services:
  gateway-service:
    build:
      context: ./../gateway-service
      dockerfile: ./../gateway-service/gateway-service.dockerfile
    ports:
      - "9999:80"
    deploy:
      mode: replicated
      replicas: 1
    restart: always

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    ports:
      - "8999:80"
    deploy:
      mode: replicated
      replicas: 1
    restart: always

  postgres-gateway:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gateway-service
    restart: always
    volumes:
      - ./db-data/postgres-gateway/:/var/lib/postgresql/data/

  postgres-authentication:
    image: 'postgres:14.2'
    ports:
      - "6432:6432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: authentication-service
    restart: always
    volumes:
      - ./db-data/postgres-authentication/:/var/lib/postgresql/data/
  