version: "3.8"

services:
  gateway-service:
    build:
      context: ./..
      dockerfile: ./gateway-service.dockerfile
    ports:
      - "9000:80"
    deploy:
      mode: replicated
      replicas: 1
    restart: always

  postgres-1:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gateway-service
    restart: always
    volumes:
      - ./db-data/postgres-1/:/var/lib/postgresql/data/
  